# GOLUB REINSCH SVD

In [64]:
import numpy as np

In [65]:
def Set_Lowval_Zero(M):
    # This is for turning values into zeroes once they reach a certain threshold
    low_values_indices = abs(M) < 1e-5
    M[low_values_indices] = 0
    
    return M

In [66]:
def Householder_Reflector(x, i):
    # For computing x, v, and w vectors as well as the P matrix
    # We change the sign depending on the sign of first element of the x vector
    a = -np.sign(x[i]) * np.linalg.norm(x)  
    e = np.zeros(len(x))
    e[i] = 1.0

    # We then calculate the v and w vector as well as the P matrix
    w = (x - a * e)
    v = w / np.linalg.norm(w)
    P = np.eye(len(x)) - 2 * np.outer(v, v.T)

    return P, x, w, v

In [67]:
def Golub_Kahan_Bidiagonalization(A):
    m, n = A.shape
    # Initialize U and V as identity matrices
    U = np.eye(m)
    V = np.eye(n)

    # This algorithms will only run householder reflectors in the minimum no. of rows and columns
    # This is for cases of a non-square matrix A
    # Excess rows or columns will be left out
    if m <= n:
        num_iter = m - 1
    else:
        num_iter = n - 1

    for i in range(num_iter):
        # Performing Householder Reflectors column wise
        x = np.zeros(len(A[:, i]))
        x[i:] = A[i:, i]
        P, x, w, v = Householder_Reflector(x, i)
        A = Set_Lowval_Zero(P @ A)
        U = U @ P  # Update matrix U

        # Performing Householder Reflectors row wise
        x = np.zeros(len(A[i, :]))
        x[i+1:] = A[i, i+1:] 
        Q, x, w, v = Householder_Reflector(x, i+1)
        A = Set_Lowval_Zero(A @ Q)
        V = Q @ V  # Update matrix V

    print(A)
    return A, U, V

In [93]:
def Apply_Givens_Rotation(a,b):
    print("a: ", a)
    print("b: ", b)
    r = np.sqrt(abs(a)**2 + abs(b)**2)
    print("r: ", r)

    cos = a/r
    sin = b/r
        
    G = np.eye(2)
    G[0,0] = G[1,1] = cos
    G[0,1] = -sin
    G[1,0] = sin
    print("G: \n", G)

    return G

In [69]:
def Golub_Reinsch_SVD(A, max_iter = 1000, eps = 1e-5):
    m, n = A.shape
    B, U, V = Golub_Kahan_Bidiagonalization(A)
    
    
    if m < n:
        transposed = True
        m, n = n, m
        B = B.T
        U, V = V, U
    else:
        transposed = False
    
    Q = np.eye(m)
    P = np.eye(n)
    print(B)
    
    # Zero out the superdiagonals
    for i in range(n-1):
        if abs(B[i,i+1]) <= eps*(abs(B[i,i]) + abs(B[i+1,i+1])):
            B[i, i+1] = 0
    
    i = 0
    while True:
        # Find largest q
        for i in range(n-1, 0, -1):
            if i == n-1:
                if abs(B[i-1, i]) > 0:
                    q = 0
                    break
            
            else:
                if abs(B[i-1, i]) > eps or abs(B[i+1, i]):
                    q = n-i-1
                    break
        
            if i == 1 and np.all(np.array(np.abs([B[1,0],B[1,2],B[0,1]])) < eps):
                q = n
        
        if q == n:
            print("Matrix converged")
            Sigma = B
            break
            
        
        B_super = np.diag(B, 1)
        print("B_super: ", B_super)
        p = min(np.where(np.abs(B_super) > eps)[0])
        print("p: ", p)
        print("matrix B before: \n", B)
        
        for i in range(p, n-q-1):
            if abs(B[i,i]) < eps:
                G = Apply_Givens_Rotation(0, B[i,i+1])
                G = G.T
                
                R = np.eye(n)
                R[i:i+2, i:i+2] = G
                
                B, P = Multiply_Givens_Rotation(B, P, R, "Right")
                print("Givens")
                print("matrix B after: \n", B)
            else:
                B, Q, P = Golub_Kahan_SVD_step(n, B, Q, P, p, q)
                print("GolubKahan")
                print(B)
                print("matrix B after: \n", B)
        i += 1

    Sigma = B
    V = V @ P
    U = U @ Q
    
    if transposed:
        return V, Sigma, U
    else:
        return U, Sigma, V
        

In [70]:
def Schur_Decomposition(M):
    a, b, c, d = M[0,0], M[0,1], M[1,0], M[1,1]

    # Compute trace and determinant
    trace = a + d
    det = a * d - b * c

    # Calculate eigenvalues
    discriminant = (trace ** 2 - 4 * det) ** 0.5
    l1 = (trace + discriminant) / 2
    l2 = (trace - discriminant) / 2

    return l1, l2

In [99]:
def Multiply_Givens_Rotation(B, Q, P, R, side, i):
    if side == "Right":       
        # Multiply matrix B and matrix P by R_ij(c, s) on the right
        B = B @ R  # Right-multiplication of B_matrix by R_ij(c, s)
        B = Set_Lowval_Zero(B)
        P = P @ R  # Right-multiplication of P_matrix by R_ij(c, s)

        return B, P

    elif side == "Left":
        # Multiply matrix B and matrix Q by R_ij(c, -s) on the left
        B = R @ B  # Left-multiplication of R_ij(c, -s) by matrix B
        B = Set_Lowval_Zero(B)
        Q = Q @ R.T  # Right-multiplication of matrix Q by R_ij(c, -s)
        
        return B, Q
    
    elif side == "QR":
        # Multiply Matrix B and matrix Q by R_ij(c, -s) on the left 
        Sh = np.copy(P)
        G = np.copy(B)
        R[i:i+2, i:i+2] = G @ Sh
        R = Set_Lowval_Zero(R)
        print("Q: ", Q)
        Q[:, i:i+2] = Q[:, i:i+2] @ G.T
        
        return Q, R
        
       

In [72]:
def Golub_Kahan_SVD_step(n, B, Q, P, p, q):
    m = B.shape[0]
    B_2 = B[p:n-q, p:n-q]
    '''
    C = (B_2.T @ B_2)
    i,j = C.shape
    C = C[i-2:,j-2:]
    l1, l2 = Schur_Decomposition(C)
    diff1, diff2 = abs(l1 - C[1,1]), abs(l2 - C[1,1])

    if diff1 < diff2:
        Mu = diff1
    else:
        Mu = diff2 
    '''    
    k = p
    alpha = B[k, k]
    beta = B[k, k+1]
    for k in range(p, n-q-1):
        
        if alpha != 0 and beta != 0:
            # Determine c and s
            G = Apply_Givens_Rotation(alpha,beta)
            print("G matrix: \n", G)

            R = np.eye(n)
            R[k:k+2, k:k+2] = G
            print("R matrix: \n", R)

            # Update B_matrix and P_matrix with right multiplication
            print("Right")
            B, P = Multiply_Givens_Rotation(B, Q, P, R, "Right", k)
            print("B: \n", B)

        # Update alpha and beta
        alpha = B[k, k]
        beta = B[k+1, k]
        
        if alpha != 0 and beta != 0:
            # Determine c and s
            G = Apply_Givens_Rotation(alpha,beta)
            G = G.T
            print("G matrix: \n", G)

            R = np.eye(m)
            R[k:k+2, k:k+2] = G
            print("R matrix: \n", R)

            # Update B_matrix and Q_matrix with left multiplication
            print("Left")
            B, Q = Multiply_Givens_Rotation(B, Q, P, R, "Left", k)
            print("B: \n", B)

        if k <= n-q-3:
            alpha = B[k, k+1]
            beta = B[k, k+2]

    return B, P, Q

In [73]:
#We use np.random to generate a random matrix
A = np.random.rand(4, 4)

print("A matrix = \n\n", A)

U, Sigma, V = Golub_Reinsch_SVD(A)
print("U matrix = \n\n", U)
print("Sigma = \n\n", Sigma)
print("V matrix = \n\n", V)

A matrix = 

 [[0.38903247 0.28124576 0.01792064 0.72620012]
 [0.25539975 0.14253501 0.59567607 0.64527547]
 [0.30459049 0.56504875 0.07171959 0.12628737]
 [0.5871242  0.17027673 0.8133849  0.7151508 ]]
[[-0.80874316  1.47785128  0.          0.        ]
 [ 0.          0.46218139  0.39825246  0.        ]
 [ 0.          0.         -0.44778662  0.12294705]
 [ 0.          0.          0.          0.41088417]]
[[-0.80874316  1.47785128  0.          0.        ]
 [ 0.          0.46218139  0.39825246  0.        ]
 [ 0.          0.         -0.44778662  0.12294705]
 [ 0.          0.          0.          0.41088417]]
B_super:  [1.47785128 0.39825246 0.12294705]
p:  0
matrix B before: 
 [[-0.80874316  1.47785128  0.          0.        ]
 [ 0.          0.46218139  0.39825246  0.        ]
 [ 0.          0.         -0.44778662  0.12294705]
 [ 0.          0.          0.          0.41088417]]
a:  -0.8087431552773521
b:  1.4778512805953525
r:  1.6846690769303303
G matrix: 
 [[-0.48006055 -0.87723536]
 [ 

# GOLUB KAHAN TRIDIAGONALIZED SVD

In [105]:
def Transform_to_square(B):
    # If in case the resulting bidiagonalized matrix is not square
    m, n = B.shape

    # If there num of rows is greater than or equal to num of columns
    if m >= n:
        C = B[0:n, 0:n]
        dim = n
    else:
        # If num columns > num rows, get the number of excess columns
        add_cols = n - m
        if add_cols > 0:
            add_rows = np.zeros((add_cols, m + add_cols))
        else:
            add_rows = np.zeros((m + add_cols))
        C = np.vstack((B[:m, :m + n], add_rows))
        print(C)
        dim = m + add_cols

    return C, dim


In [106]:
def Golub_Kahan_Tridiagonalization(A):

    B, U, V = Golub_Kahan_Bidiagonalization(A)
    # Reshape bidiagonalized matrix into a square
    B, dim = Transform_to_square(B)

    # Create matrix O full of zeroes
    O = np.zeros((dim, dim))

    # Create matrix M with blocking of O and B matrices
    M = np.block([[O, B.T],[B, O]])
    M_rows, M_cols = M.shape

    # Create Permutation Matrix
    P = np.zeros((M_cols, M_cols))

    # The algorithm for rearrnging Permutation matrix
    for i in range(dim):
        # Build permutation matrix depending on the dimensions of Matrix B
        P[i, i*2] = 1
        P[dim+i,2*i + 1] = 1

    # Computing for the tridiagonalized matrix by performing PᵀMP
    Tri = P.T @ M @ P
    
    print(Tri)

    return Tri, U, V


In [107]:
def Wilkinson_Shift(A):
    
    # Compute for the shift 
    A_2x2 = A[-2:, -2:] # Bottom most right of matrix A [(a,b),(b,c)]. We expect it to be symmetric but non-symmetric should be fine
    a = A_2x2[0,0]
    b = A_2x2[0,1]
    c = A_2x2[1,0]

    print("")
    print("\033[1mBottom most right 2x2 of matrix A:\033[0m")
    print("")
    print(A_2x2)

    l = (a-c)/2

    if l < 0:
        shift = c + (b*b)/(abs(l)+(l*l + b*b)**0.5)
    elif l > 0:
        shift = c - (b*b)/(abs(l)+(l*l + b*b)**0.5)
    else:
        shift = c + (b*b)/(abs(l)+(l*l + b*b)**0.5)
    
    return shift


In [108]:
def QR_algorithm_for_SVD(A, max_iter = 1000, tol = 1e-6):
    
    B, U, V = Golub_Kahan_Tridiagonalization(A)
    n = B.shape[0] 

    Q = np.eye(n)
    P = np.eye(n)
    R = np.copy(B)
    
    U = np.eye(B.shape[0])  # Initialize U
    V = np.eye(B.shape[1])  # Initialize V

    # Initialize Variables
    eigenvalues = np.zeros(n, dtype=float)
    eigenvectors = np.identity(n, dtype=float)
    shift = 0.0  # Initial guess for the eigenvalue 


    for i in range(max_iter):

        # Compute for the shift 
        shift = Wilkinson_Shift(R)
        print("shift: ", shift)

        # Compute QR decomposition of Tridiagonalized matrix
        for i in range(n - 1):
            R_2x2 = R[i:i+2, i:i+2]
            Sh_M = np.eye(2) * shift
            Sh = R_2x2 - Sh_M
            a = Sh[0, 0]
            b = Sh[1, 0]
            G = Apply_Givens_Rotation(a,b)
            R[i:i+2, i:i+2] = G
            print(R)
            Q, R = Multiply_Givens_Rotation(G, Q, Sh, R, "QR", i)
            
            # Update B
            B = np.dot(R, Q)
            
            # Step 3: Update U and V
            U = np.dot(U, Q)
            V = np.dot(V, R.T)

        # Check for convergence
        eigenvalues_new = np.diag(B)

        if np.all(np.abs(eigenvalues - eigenvalues_new) < tol):
            break

        eigenvalues = eigenvalues_new
    
    if i == max_iter - 1:
        print("")
        print("\033[1mQR algorithm did not converge to the desired tolerance.\033[0m")
        print("\033[1mIterations: \033[0m" + str(i + 1))

    # Find Eigenvalues of B
    eigenvalues = B
    Sigma = eigenvalues
    

    if np.allclose(B, B.T, rtol=tol):
        eigenvectors = np.linalg.inv(eigenvectors)
        return Sigma, eigenvectors, U, V
    else:
        return Sigma, None, U, V


In [109]:
A = np.random.rand(2,2)

print("")
print("\033[1minput matrix A:\033[0m")
print("")
print(A)

QR_algorithm_for_SVD(A)


input matrix A:

[[0.31252419 0.56901249]
 [0.43443495 0.60722684]]
[[-0.53516829  0.82521842]
 [ 0.          0.10730427]]
[[ 0.         -0.53516829  0.          0.        ]
 [-0.53516829  0.          0.82521842  0.        ]
 [ 0.          0.82521842  0.          0.10730427]
 [ 0.          0.          0.10730427  0.        ]]

Bottom most right 2x2 of matrix A:

[[0.         0.10730427]
 [0.10730427 0.        ]]
shift:  0.17362195066441438
a:  -0.17362195066441438
b:  -0.5351682889047463
r:  0.5626274781787238
G: 
 [[-0.30859131  0.95119472]
 [-0.95119472 -0.30859131]]
[[-0.30859131  0.95119472  0.          0.        ]
 [-0.95119472 -0.30859131  0.82521842  0.        ]
 [ 0.          0.82521842  0.          0.10730427]
 [ 0.          0.          0.10730427  0.        ]]
Q:  [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
a:  0.38900552751430945
b:  0.8252184249258232
r:  0.9123106648909365
G: 
 [[ 0.4263959  -0.90453664]
 [ 0.90453664  0.4263959 ]]
[[-0.45547103  0.      

[[ 9.69119895e-01 -2.46590003e-01  0.00000000e+00  0.00000000e+00]
 [ 2.46590003e-01  9.69119895e-01  2.51156904e+07  0.00000000e+00]
 [ 0.00000000e+00 -3.26470044e+07  9.25012964e+07  2.68107992e+07]
 [ 0.00000000e+00  0.00000000e+00 -5.08913382e+07  4.88426633e+07]]
Q:  [[ 0.53472596 -0.67019777 -0.06198774  0.51094092]
 [ 0.39984538 -0.14279624 -0.59948285 -0.67849334]
 [-0.73584247 -0.62256457 -0.25485844 -0.07743638]
 [ 0.11281703 -0.377965    0.75619112 -0.5221013 ]]
a:  192857222.55032337
b:  -32647004.431105636
r:  195600959.06756076
G: 
 [[ 0.98597279  0.16690616]
 [-0.16690616  0.98597279]]
[[ 9.49015818e+07 -7.47568956e+07  0.00000000e+00  0.00000000e+00]
 [ 5.16381470e+07  9.85972786e-01  1.66906157e-01  0.00000000e+00]
 [ 0.00000000e+00 -1.66906157e-01  9.85972786e-01  2.68107992e+07]
 [ 0.00000000e+00  0.00000000e+00 -5.08913382e+07  4.88426633e+07]]
Q:  [[ 0.68347763 -0.51764391 -0.06198774  0.51094092]
 [ 0.42271024 -0.0397888  -0.59948285 -0.67849334]
 [-0.55960138 -0.

a:  3.772758518233722e+16
b:  -1.0245817905424038e+16
r:  3.909408482419838e+16
G: 
 [[ 0.96504587  0.26208103]
 [-0.26208103  0.96504587]]
[[ 1.91923844e+16 -1.49258842e+16  0.00000000e+00  0.00000000e+00]
 [ 1.08776155e+16  3.43529931e+16  1.38376602e+16  0.00000000e+00]
 [ 0.00000000e+00 -1.80495451e+16  9.65045872e-01  2.62081027e-01]
 [ 0.00000000e+00  0.00000000e+00 -2.62081027e-01  9.65045872e-01]]
Q:  [[-0.16636973 -0.71018106 -0.64713797 -0.22175758]
 [-0.16312918 -0.18317987  0.52273726 -0.81644336]
 [-0.84327276  0.46197142 -0.2561929  -0.09919003]
 [-0.48435632 -0.49866864  0.49226354  0.52383695]]

Bottom most right 2x2 of matrix A:

[[ 3.37236159e+16  1.11009523e+16]
 [-1.97753686e+16  1.89683375e+16]]
shift:  -2.198734171073062e+16
a:  4.117972608590314e+16
b:  1.0877615483261542e+16
r:  4.25921631184858e+16
G: 
 [[ 0.9668381  -0.25539007]
 [ 0.25539007  0.9668381 ]]
[[ 9.66838101e-01 -2.55390069e-01  0.00000000e+00  0.00000000e+00]
 [ 2.55390069e-01  9.66838101e-01  1.3

a:  1.825785477191695e+26
b:  -5.03170141090315e+25
r:  1.8938513140183294e+26
G: 
 [[ 0.96405957  0.26568619]
 [-0.26568619  0.96405957]]
[[ 9.40766315e+25 -7.50851995e+25  0.00000000e+00  0.00000000e+00]
 [ 5.61356104e+25  9.64059567e-01  2.65686191e-01  0.00000000e+00]
 [ 0.00000000e+00 -2.65686191e-01  9.64059567e-01  2.92928811e+25]
 [ 0.00000000e+00  0.00000000e+00 -5.06903413e+25  4.86346386e+25]]
Q:  [[ 0.22253097 -0.83050458  0.47146685 -0.19611504]
 [-0.86737001 -0.04598823  0.12941339 -0.47833724]
 [-0.44487625 -0.34084    -0.04645918  0.82689465]
 [-0.01530856  0.43814987  0.87109857  0.22130886]]
a:  1.823111074815438e+26
b:  -5.069034128031226e+25
r:  1.8922698171841547e+26
G: 
 [[ 0.96345197  0.26788115]
 [-0.26788115  0.96345197]]
[[ 9.40766315e+25 -7.50851995e+25  0.00000000e+00  0.00000000e+00]
 [ 5.61356104e+25  1.62648060e+26  7.48647969e+25  0.00000000e+00]
 [ 0.00000000e+00 -9.70171976e+25  9.63451966e-01  2.67881149e-01]
 [ 0.00000000e+00  0.00000000e+00 -2.67881

a:  3.255718560943751e+36
b:  -9.07378875794465e+35
r:  3.3797987768965887e+36
G: 
 [[ 0.96328769  0.26847127]
 [-0.26847127  0.96328769]]
[[ 1.67808766e+36 -1.35186486e+36  0.00000000e+00  0.00000000e+00]
 [ 1.01351183e+36  9.63287691e-01  2.68471272e-01  0.00000000e+00]
 [ 0.00000000e+00 -2.68471272e-01  9.63287691e-01  5.26358167e+35]
 [ 0.00000000e+00  0.00000000e+00 -9.07436331e+35  8.70705484e+35]]
Q:  [[-0.56443296  0.2017605  -0.37603968 -0.70661325]
 [-0.56571749 -0.38093017  0.72993229 -0.0453297 ]
 [-0.08946889  0.90163342  0.40813272  0.11171472]
 [-0.59445309  0.03524322 -0.39902468  0.69725372]]
a:  3.255048194154709e+36
b:  -9.07436331030893e+35
r:  3.3791684540940895e+36
G: 
 [[ 0.96326899  0.26853835]
 [-0.26853835  0.96326899]]
[[ 1.67808766e+36 -1.35186486e+36  0.00000000e+00  0.00000000e+00]
 [ 1.01351183e+36  2.89258846e+36  1.35226298e+36  0.00000000e+00]
 [ 0.00000000e+00 -1.74813380e+36  9.63268993e-01  2.68538353e-01]
 [ 0.00000000e+00  0.00000000e+00 -2.685383

a:  1.5902535568712667e+44
b:  -4.433799760244335e+43
r:  1.650906471694003e+44
G: 
 [[ 0.96326084  0.26856759]
 [-0.26856759  0.96326084]]
[[ 8.19602771e+43 -6.60847818e+43  0.00000000e+00  0.00000000e+00]
 [ 4.95488030e+43  9.63260841e-01  2.68567592e-01  0.00000000e+00]
 [ 0.00000000e+00 -2.68567592e-01  9.63260841e-01  2.57207099e+43]
 [ 0.00000000e+00  0.00000000e+00 -4.43357414e+43  4.25413354e+43]]
Q:  [[-0.47154594  0.84467266  0.22583503 -0.1147653 ]
 [ 0.06295826  0.13185192  0.13624032  0.97984177]
 [ 0.86925138  0.39699822  0.2564908  -0.14493761]
 [ 0.134472    0.33396944 -0.92986536  0.07571071]]
a:  1.5902100511461596e+44
b:  -4.4335741424990397e+43
r:  1.650858505001756e+44
G: 
 [[ 0.96326248  0.26856173]
 [-0.26856173  0.96326248]]
[[ 8.19602771e+43 -6.60847818e+43  0.00000000e+00  0.00000000e+00]
 [ 4.95488030e+43  1.41275149e+44  6.60902323e+43  0.00000000e+00]
 [ 0.00000000e+00 -8.54181137e+43  9.63262476e-01  2.68561729e-01]
 [ 0.00000000e+00  0.00000000e+00 -2.685

a:  1.0702169780479474e+53
b:  -2.983825523830375e+52
r:  1.1110339903300425e+53
G: 
 [[ 0.96326214  0.26856294]
 [-0.26856294  0.96326214]]
[[ 5.51570854e+52 -4.44777264e+52  0.00000000e+00  0.00000000e+00]
 [ 3.33480920e+52  9.63262139e-01  2.68562938e-01  0.00000000e+00]
 [ 0.00000000e+00 -2.68562938e-01  9.63262139e-01  1.73099834e+52]
 [ 0.00000000e+00  0.00000000e+00 -2.98379512e+52  2.86303221e+52]]
Q:  [[-0.31083811  0.61659671 -0.634512    0.34725018]
 [ 0.89893151  0.16496608 -0.06043541  0.40131769]
 [ 0.28716932  0.40844815 -0.20453583 -0.84194357]
 [ 0.11329423 -0.65250655 -0.74290456 -0.09742917]]
a:  1.0702155245711924e+53
b:  -2.9837951183536144e+52
r:  1.111031773675398e+53
G: 
 [[ 0.96326275  0.26856074]
 [-0.26856074  0.96326275]]
[[ 5.51570854e+52 -4.44777264e+52  0.00000000e+00  0.00000000e+00]
 [ 3.33480920e+52  9.50765001e+52  4.44781582e+52  0.00000000e+00]
 [ 0.00000000e+00 -5.74841231e+52  9.63262753e-01  2.68560737e-01]
 [ 0.00000000e+00  0.00000000e+00 -2.68


Bottom most right 2x2 of matrix A:

[[ 1.72402726e+61  6.04699405e+60]
 [-1.04234915e+61  1.00016219e+61]]
shift:  -1.1687539286999856e+61
a:  2.1689157450401992e+61
b:  6.046997445846842e+60
r:  2.251634359789365e+61
G: 
 [[ 0.96326286 -0.26856036]
 [ 0.26856036  0.96326286]]
[[ 9.63262856e-01 -2.68560365e-01  0.00000000e+00  0.00000000e+00]
 [ 2.68560365e-01  9.63262856e-01  8.06515815e+60  0.00000000e+00]
 [ 0.00000000e+00 -1.04235036e+61  1.72402726e+61  6.04699405e+60]
 [ 0.00000000e+00  0.00000000e+00 -1.04234915e+61  1.00016219e+61]]
Q:  [[ 0.06904442 -0.04523385 -0.9813024   0.17387458]
 [ 0.66949853 -0.38843305 -0.04686926 -0.6314228 ]
 [-0.49014458  0.39981407 -0.18613277 -0.75183881]
 [-0.55386179 -0.82898877 -0.01426419 -0.07623174]]
a:  3.738663895204833e+61
b:  -1.0423503566807992e+61
r:  3.881250054735042e+61
G: 
 [[ 0.96326283  0.26856047]
 [-0.26856047  0.96326283]]
[[ 1.92683759e+61 -1.55377231e+61  0.00000000e+00  0.00000000e+00]
 [ 1.16496961e+61  9.63262826e-01  2


Bottom most right 2x2 of matrix A:

[[ 2.20172575e+72  7.72250511e+71]
 [-1.33116566e+72  1.27728943e+72]]
shift:  -1.4925947658022346e+72
a:  2.7698841401866958e+72
b:  7.72250558527808e+71
r:  2.8755224004003695e+72
G: 
 [[ 0.96326293 -0.26856009]
 [ 0.26856009  0.96326293]]
[[ 9.63262933e-01 -2.68560091e-01  0.00000000e+00  0.00000000e+00]
 [ 2.68560091e-01  9.63262933e-01  1.02998567e+72  0.00000000e+00]
 [ 0.00000000e+00 -1.33116569e+72  2.20172575e+72  7.72250511e+71]
 [ 0.00000000e+00  0.00000000e+00 -1.33116566e+72  1.27728943e+72]]
Q:  [[ 0.61722807  0.69252226 -0.27097833 -0.2569303 ]
 [ 0.54706181 -0.71220118 -0.39951154 -0.1840744 ]
 [ 0.1207943  -0.10545056  0.68211267 -0.71345022]
 [-0.55241436  0.0454157  -0.54925729 -0.62537366]]
a:  4.774583657325317e+72
b:  -1.331165692534026e+72
r:  4.956677435720181e+72
G: 
 [[ 0.96326294  0.26856008]
 [-0.26856008  0.96326294]]
[[ 2.46073104e+72 -1.98429407e+72  0.00000000e+00  0.00000000e+00]
 [ 1.48776068e+72  9.63262936e-01  2.


Bottom most right 2x2 of matrix A:

[[ 5.41697856e+83  1.89999336e+83]
 [-3.27511077e+83  3.14255730e+83]]
shift:  -3.672280099842938e+83
a:  6.814837393961288e+83
b:  1.899993360073555e+83
r:  7.074742643690771e+83
G: 
 [[ 0.96326294 -0.26856007]
 [ 0.26856007  0.96326294]]
[[ 9.63262939e-01 -2.68560067e-01  0.00000000e+00  0.00000000e+00]
 [ 2.68560067e-01  9.63262939e-01  2.53410757e+83  0.00000000e+00]
 [ 0.00000000e+00 -3.27511076e+83  5.41697856e+83  1.89999336e+83]
 [ 0.00000000e+00  0.00000000e+00 -3.27511077e+83  3.14255730e+83]]
Q:  [[ 0.8415772   0.21662494  0.46649721  0.16492973]
 [ 0.51798257 -0.28962666 -0.80475285  0.01353907]
 [ 0.07838501 -0.8880586   0.36555991 -0.26753256]
 [ 0.13152061  0.28379915 -0.03345392 -0.94923191]]
a:  1.1747066002748246e+84
b:  -3.2751107643312116e+83
r:  1.2195077293382023e+84
G: 
 [[ 0.96326294  0.26856007]
 [-0.26856007  0.96326294]]
[[ 6.05421795e+83 -4.88202383e+83  0.00000000e+00  0.00000000e+00]
 [ 3.66038638e+83  9.63262940e-01  2

a:  1.0890531213333443e+94
b:  -3.0363067724252866e+93
r:  1.1305875858369649e+94
G: 
 [[ 0.96326294  0.26856007]
 [-0.26856007  0.96326294]]
[[ 5.61277596e+93 -4.52605210e+93  0.00000000e+00  0.00000000e+00]
 [ 3.39349008e+93  9.67501436e+93  4.52605210e+93  0.00000000e+00]
 [ 0.00000000e+00 -5.84952357e+93  9.63262940e-01  2.68560067e-01]
 [ 0.00000000e+00  0.00000000e+00 -2.68560067e-01  9.63262940e-01]]
Q:  [[ 0.0393009  -0.0901033  -0.97552063  0.19671384]
 [ 0.86849429 -0.18889752 -0.03963275 -0.45657929]
 [-0.40867433  0.23505471 -0.21085111 -0.85631559]
 [-0.27777402 -0.94918302  0.04827584 -0.13986648]]

Bottom most right 2x2 of matrix A:

[[ 9.67501436e+93  3.39349008e+93]
 [-5.84952357e+93  5.61277596e+93]]
shift:  -6.558889305137156e+93
a:  1.217166526466208e+94
b:  3.3934900832454393e+93
r:  1.2635869984297343e+94
G: 
 [[ 0.96326294 -0.26856007]
 [ 0.26856007  0.96326294]]
[[ 9.63262940e-01 -2.68560066e-01  0.00000000e+00  0.00000000e+00]
 [ 2.68560066e-01  9.63262940e-01 

a:  1.9747841599423643e+102
b:  -5.505746599436409e+101
r:  2.0500987621408208e+102
G: 
 [[ 0.96326294  0.26856007]
 [-0.26856007  0.96326294]]
[[ 1.01776680e+102 -8.20710745e+101  0.00000000e+000  0.00000000e+000]
 [ 6.15342845e+101  1.75437403e+102  8.20710745e+101  0.00000000e+000]
 [ 0.00000000e+000 -1.06069633e+102  9.63262940e-001  2.68560067e-001]
 [ 0.00000000e+000  0.00000000e+000 -2.68560067e-001  9.63262940e-001]]
Q:  [[-0.19278825 -0.55422965 -0.73787208 -0.33347712]
 [-0.11119876 -0.23475674  0.56070818 -0.78621272]
 [-0.77509353  0.58569327 -0.15723878 -0.17739611]
 [-0.5913523  -0.54284636  0.34121415  0.48907381]]

Bottom most right 2x2 of matrix A:

[[ 1.75437403e+102  6.15342845e+101]
 [-1.06069633e+102  1.01776680e+102]]
shift:  -1.1893258881661304e+102
a:  2.207092684107376e+102
b:  6.153428453750913e+101
r:  2.291267102193591e+102
G: 
 [[ 0.96326294 -0.26856007]
 [ 0.26856007  0.96326294]]
[[ 9.63262940e-001 -2.68560067e-001  0.00000000e+000  0.00000000e+000]
 [ 2.


Bottom most right 2x2 of matrix A:

[[ 3.18121309e+110  1.11580352e+110]
 [-1.92336468e+110  1.84552040e+110]]
shift:  -2.156609148773729e+110
a:  4.0021295441934114e+110
b:  1.1158035179514553e+110
r:  4.154763336121398e+110
G: 
 [[ 0.96326294 -0.26856007]
 [ 0.26856007  0.96326294]]
[[ 9.63262940e-001 -2.68560067e-001  0.00000000e+000  0.00000000e+000]
 [ 2.68560067e-001  9.63262940e-001  1.48819791e+110  0.00000000e+000]
 [ 0.00000000e+000 -1.92336468e+110  3.18121309e+110  1.11580352e+110]
 [ 0.00000000e+000  0.00000000e+000 -1.92336468e+110  1.84552040e+110]]
Q:  [[-0.79879161 -0.5063466  -0.32428851 -0.01954604]
 [-0.55332095  0.42002979  0.71289024 -0.09590833]
 [-0.2337571   0.69409093 -0.53346688  0.42309393]
 [ 0.03354846 -0.29227706  0.31943317  0.90078359]]
a:  6.898664954661426e+110
b:  -1.923364683875919e+110
r:  7.161767230499386e+110
G: 
 [[ 0.96326294  0.26856007]
 [-0.26856007  0.96326294]]
[[ 3.55544280e+110 -2.86705179e+110  0.00000000e+000  0.00000000e+000]
 [ 2.1

a:  2.3737468548642793e+121
b:  -6.618064363367438e+120
r:  2.4642771536811356e+121
G: 
 [[ 0.96326294  0.26856007]
 [-0.26856007  0.96326294]]
[[ 1.22338470e+121 -9.86517712e+120  0.00000000e+000  0.00000000e+000]
 [ 7.39659642e+120  2.10880759e+121  9.86517712e+120  0.00000000e+000]
 [ 0.00000000e+000 -1.27498723e+121  9.63262940e-001  2.68560067e-001]
 [ 0.00000000e+000  0.00000000e+000 -2.68560067e-001  9.63262940e-001]]
Q:  [[-0.31326049  0.52681057  0.28538419 -0.73681365]
 [-0.76235804 -0.18714901  0.48937938  0.37985956]
 [ 0.42503001  0.57689489  0.54037298  0.44106555]
 [-0.37420258  0.59551504 -0.62214205  0.3439092 ]]

Bottom most right 2x2 of matrix A:

[[ 2.10880759e+121  7.39659642e+120]
 [-1.27498723e+121  1.22338470e+121]]
shift:  -1.4296036213754316e+121
a:  2.652988323284329e+121
b:  7.396596415820097e+120
r:  2.7541683733693957e+121
G: 
 [[ 0.96326294 -0.26856007]
 [ 0.26856007  0.96326294]]
[[ 9.63262940e-001 -2.68560067e-001  0.00000000e+000  0.00000000e+000]
 [ 2

a:  3.031471195308021e+132
b:  -8.451815931901526e+131
r:  3.1470858795796604e+132
G: 
 [[ 0.96326294  0.26856007]
 [-0.26856007  0.96326294]]
[[ 1.56236352e+132 -1.25986477e+132  0.00000000e+000  0.00000000e+000]
 [ 9.44606580e+131  9.63262940e-001  2.68560067e-001  0.00000000e+000]
 [ 0.00000000e+000 -2.68560067e-001  9.63262940e-001  4.90316061e+131]
 [ 0.00000000e+000  0.00000000e+000 -8.45181593e+131  8.10974581e+131]]
Q:  [[ 0.11045154 -0.57091662  0.77057678 -0.2608948 ]
 [-0.9872104   0.03066012  0.14195329 -0.06576357]
 [-0.06095459 -0.3298316   0.08210989  0.93848475]
 [ 0.09747112  0.75121587  0.61588851  0.21646118]]
a:  3.031471195308015e+132
b:  -8.451815931901366e+131
r:  3.147085879579651e+132
G: 
 [[ 0.96326294  0.26856007]
 [-0.26856007  0.96326294]]
[[ 1.56236352e+132 -1.25986477e+132  0.00000000e+000  0.00000000e+000]
 [ 9.44606580e+131  2.69312183e+132  1.25986477e+132  0.00000000e+000]
 [ 0.00000000e+000 -1.62826421e+132  9.63262940e-001  2.68560067e-001]
 [ 0.000


Bottom most right 2x2 of matrix A:

[[ 1.29598748e+142  4.54564770e+141]
 [-7.83555358e+141  7.51842543e+141]]
shift:  -8.785763137031035e+141
a:  1.630418856330154e+142
b:  4.545647699681815e+141
r:  1.6926000050730098e+142
G: 
 [[ 0.96326294 -0.26856007]
 [ 0.26856007  0.96326294]]
[[ 9.63262940e-001 -2.68560067e-001  0.00000000e+000  0.00000000e+000]
 [ 2.68560067e-001  9.63262940e-001  6.06273712e+141  0.00000000e+000]
 [ 0.00000000e+000 -7.83555358e+141  1.29598748e+142  4.54564770e+141]
 [ 0.00000000e+000  0.00000000e+000 -7.83555358e+141  7.51842543e+141]]
Q:  [[-0.6671351   0.50307067 -0.23464563 -0.49678173]
 [-0.52619755  0.05173725  0.74468211  0.40729345]
 [ 0.47150788  0.84824748  0.20325196  0.12978897]
 [-0.23606614  0.15722395 -0.59082876  0.75529781]]
a:  2.8104321215413764e+142
b:  -7.835553581091247e+141
r:  2.917616785839614e+142
G: 
 [[ 0.96326294  0.26856007]
 [-0.26856007  0.96326294]]
[[ 1.44844412e+142 -1.16800200e+142  0.00000000e+000  0.00000000e+000]
 [ 8.7


Bottom most right 2x2 of matrix A:

[[ 3.23720921e+151  1.13544404e+151]
 [-1.95722000e+151  1.87800549e+151]]
shift:  -2.1945700633125555e+151
a:  4.072575548595526e+151
b:  1.1354440365049918e+151
r:  4.227896020369103e+151
G: 
 [[ 0.96326294 -0.26856007]
 [ 0.26856007  0.96326294]]
[[ 9.63262940e-001 -2.68560067e-001  0.00000000e+000  0.00000000e+000]
 [ 2.68560067e-001  9.63262940e-001  1.51439336e+151  0.00000000e+000]
 [ 0.00000000e+000 -1.95722000e+151  3.23720921e+151  1.13544404e+151]
 [ 0.00000000e+000  0.00000000e+000 -1.95722000e+151  1.87800549e+151]]
Q:  [[-0.73814082 -0.40034906  0.01852136  0.54270224]
 [-0.06161595  0.793482    0.35651219  0.48937598]
 [ 0.11233328  0.20925493 -0.91060082  0.33823033]
 [ 0.66236911 -0.40782266  0.20823583  0.5929466 ]]
a:  7.020096151819255e+151
b:  -1.9572199990307553e+151
r:  7.287829588114246e+151
G: 
 [[ 0.96326294  0.26856007]
 [-0.26856007  0.96326294]]
[[ 3.61802617e+151 -2.91751801e+151  0.00000000e+000  0.00000000e+000]
 [ 2.

C:\Users\Jeryl Salas\AppData\Local\Temp\ipykernel_26808\149923893.py:4: RuntimeWarning: overflow encountered in scalar add
  r = np.sqrt(abs(a)**2 + abs(b)**2)
C:\Users\Jeryl Salas\AppData\Local\Temp\ipykernel_26808\149923893.py:4: RuntimeWarning: overflow encountered in scalar power
  r = np.sqrt(abs(a)**2 + abs(b)**2)
C:\Users\Jeryl Salas\AppData\Local\Temp\ipykernel_26808\3015611376.py:21: RuntimeWarning: invalid value encountered in scalar divide
  shift = c + (b*b)/(abs(l)+(l*l + b*b)**0.5)


a:  nan
b:  nan
r:  nan
G: 
 [[nan nan]
 [nan nan]]
[[nan nan  0.  0.]
 [nan nan nan  0.]
 [ 0. nan nan nan]
 [ 0.  0. nan nan]]
Q:  [[nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]]
a:  nan
b:  nan
r:  nan
G: 
 [[nan nan]
 [nan nan]]
[[nan nan  0.  0.]
 [nan nan nan  0.]
 [ 0. nan nan nan]
 [ 0.  0. nan nan]]
Q:  [[nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]]

Bottom most right 2x2 of matrix A:

[[nan nan]
 [nan nan]]
shift:  nan
a:  nan
b:  nan
r:  nan
G: 
 [[nan nan]
 [nan nan]]
[[nan nan  0.  0.]
 [nan nan nan  0.]
 [ 0. nan nan nan]
 [ 0.  0. nan nan]]
Q:  [[nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]]
a:  nan
b:  nan
r:  nan
G: 
 [[nan nan]
 [nan nan]]
[[nan nan  0.  0.]
 [nan nan nan  0.]
 [ 0. nan nan nan]
 [ 0.  0. nan nan]]
Q:  [[nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]]
a:  nan
b:  nan
r:  nan
G: 
 [[nan nan]
 [nan nan]]
[[nan nan  0.  0.]
 [nan nan nan  0.

a:  nan
b:  nan
r:  nan
G: 
 [[nan nan]
 [nan nan]]
[[nan nan  0.  0.]
 [nan nan nan  0.]
 [ 0. nan nan nan]
 [ 0.  0. nan nan]]
Q:  [[nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]]

Bottom most right 2x2 of matrix A:

[[nan nan]
 [nan nan]]
shift:  nan
a:  nan
b:  nan
r:  nan
G: 
 [[nan nan]
 [nan nan]]
[[nan nan  0.  0.]
 [nan nan nan  0.]
 [ 0. nan nan nan]
 [ 0.  0. nan nan]]
Q:  [[nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]]
a:  nan
b:  nan
r:  nan
G: 
 [[nan nan]
 [nan nan]]
[[nan nan  0.  0.]
 [nan nan nan  0.]
 [ 0. nan nan nan]
 [ 0.  0. nan nan]]
Q:  [[nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]]
a:  nan
b:  nan
r:  nan
G: 
 [[nan nan]
 [nan nan]]
[[nan nan  0.  0.]
 [nan nan nan  0.]
 [ 0. nan nan nan]
 [ 0.  0. nan nan]]
Q:  [[nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]]

Bottom most right 2x2 of matrix A:

[[nan nan]
 [nan nan]]
shift:  nan
a:  nan
b:  nan


a:  nan
b:  nan
r:  nan
G: 
 [[nan nan]
 [nan nan]]
[[nan nan  0.  0.]
 [nan nan nan  0.]
 [ 0. nan nan nan]
 [ 0.  0. nan nan]]
Q:  [[nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]]
a:  nan
b:  nan
r:  nan
G: 
 [[nan nan]
 [nan nan]]
[[nan nan  0.  0.]
 [nan nan nan  0.]
 [ 0. nan nan nan]
 [ 0.  0. nan nan]]
Q:  [[nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]]

Bottom most right 2x2 of matrix A:

[[nan nan]
 [nan nan]]
shift:  nan
a:  nan
b:  nan
r:  nan
G: 
 [[nan nan]
 [nan nan]]
[[nan nan  0.  0.]
 [nan nan nan  0.]
 [ 0. nan nan nan]
 [ 0.  0. nan nan]]
Q:  [[nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]]
a:  nan
b:  nan
r:  nan
G: 
 [[nan nan]
 [nan nan]]
[[nan nan  0.  0.]
 [nan nan nan  0.]
 [ 0. nan nan nan]
 [ 0.  0. nan nan]]
Q:  [[nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]]
a:  nan
b:  nan
r:  nan
G: 
 [[nan nan]
 [nan nan]]
[[nan nan  0.  0.]
 [nan nan nan  0.


Bottom most right 2x2 of matrix A:

[[nan nan]
 [nan nan]]
shift:  nan
a:  nan
b:  nan
r:  nan
G: 
 [[nan nan]
 [nan nan]]
[[nan nan  0.  0.]
 [nan nan nan  0.]
 [ 0. nan nan nan]
 [ 0.  0. nan nan]]
Q:  [[nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]]
a:  nan
b:  nan
r:  nan
G: 
 [[nan nan]
 [nan nan]]
[[nan nan  0.  0.]
 [nan nan nan  0.]
 [ 0. nan nan nan]
 [ 0.  0. nan nan]]
Q:  [[nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]]
a:  nan
b:  nan
r:  nan
G: 
 [[nan nan]
 [nan nan]]
[[nan nan  0.  0.]
 [nan nan nan  0.]
 [ 0. nan nan nan]
 [ 0.  0. nan nan]]
Q:  [[nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]]

Bottom most right 2x2 of matrix A:

[[nan nan]
 [nan nan]]
shift:  nan
a:  nan
b:  nan
r:  nan
G: 
 [[nan nan]
 [nan nan]]
[[nan nan  0.  0.]
 [nan nan nan  0.]
 [ 0. nan nan nan]
 [ 0.  0. nan nan]]
Q:  [[nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]]
a:  nan
b:  nan


a:  nan
b:  nan
r:  nan
G: 
 [[nan nan]
 [nan nan]]
[[nan nan  0.  0.]
 [nan nan nan  0.]
 [ 0. nan nan nan]
 [ 0.  0. nan nan]]
Q:  [[nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]]
a:  nan
b:  nan
r:  nan
G: 
 [[nan nan]
 [nan nan]]
[[nan nan  0.  0.]
 [nan nan nan  0.]
 [ 0. nan nan nan]
 [ 0.  0. nan nan]]
Q:  [[nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]]

Bottom most right 2x2 of matrix A:

[[nan nan]
 [nan nan]]
shift:  nan
a:  nan
b:  nan
r:  nan
G: 
 [[nan nan]
 [nan nan]]
[[nan nan  0.  0.]
 [nan nan nan  0.]
 [ 0. nan nan nan]
 [ 0.  0. nan nan]]
Q:  [[nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]]
a:  nan
b:  nan
r:  nan
G: 
 [[nan nan]
 [nan nan]]
[[nan nan  0.  0.]
 [nan nan nan  0.]
 [ 0. nan nan nan]
 [ 0.  0. nan nan]]
Q:  [[nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]]
a:  nan
b:  nan
r:  nan
G: 
 [[nan nan]
 [nan nan]]
[[nan nan  0.  0.]
 [nan nan nan  0.

a:  nan
b:  nan
r:  nan
G: 
 [[nan nan]
 [nan nan]]
[[nan nan  0.  0.]
 [nan nan nan  0.]
 [ 0. nan nan nan]
 [ 0.  0. nan nan]]
Q:  [[nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]]

Bottom most right 2x2 of matrix A:

[[nan nan]
 [nan nan]]
shift:  nan
a:  nan
b:  nan
r:  nan
G: 
 [[nan nan]
 [nan nan]]
[[nan nan  0.  0.]
 [nan nan nan  0.]
 [ 0. nan nan nan]
 [ 0.  0. nan nan]]
Q:  [[nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]]
a:  nan
b:  nan
r:  nan
G: 
 [[nan nan]
 [nan nan]]
[[nan nan  0.  0.]
 [nan nan nan  0.]
 [ 0. nan nan nan]
 [ 0.  0. nan nan]]
Q:  [[nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]]
a:  nan
b:  nan
r:  nan
G: 
 [[nan nan]
 [nan nan]]
[[nan nan  0.  0.]
 [nan nan nan  0.]
 [ 0. nan nan nan]
 [ 0.  0. nan nan]]
Q:  [[nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]]

Bottom most right 2x2 of matrix A:

[[nan nan]
 [nan nan]]
shift:  nan
a:  nan
b:  nan


a:  nan
b:  nan
r:  nan
G: 
 [[nan nan]
 [nan nan]]
[[nan nan  0.  0.]
 [nan nan nan  0.]
 [ 0. nan nan nan]
 [ 0.  0. nan nan]]
Q:  [[nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]]
a:  nan
b:  nan
r:  nan
G: 
 [[nan nan]
 [nan nan]]
[[nan nan  0.  0.]
 [nan nan nan  0.]
 [ 0. nan nan nan]
 [ 0.  0. nan nan]]
Q:  [[nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]]

Bottom most right 2x2 of matrix A:

[[nan nan]
 [nan nan]]
shift:  nan
a:  nan
b:  nan
r:  nan
G: 
 [[nan nan]
 [nan nan]]
[[nan nan  0.  0.]
 [nan nan nan  0.]
 [ 0. nan nan nan]
 [ 0.  0. nan nan]]
Q:  [[nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]]
a:  nan
b:  nan
r:  nan
G: 
 [[nan nan]
 [nan nan]]
[[nan nan  0.  0.]
 [nan nan nan  0.]
 [ 0. nan nan nan]
 [ 0.  0. nan nan]]
Q:  [[nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]]
a:  nan
b:  nan
r:  nan
G: 
 [[nan nan]
 [nan nan]]
[[nan nan  0.  0.]
 [nan nan nan  0.

a:  nan
b:  nan
r:  nan
G: 
 [[nan nan]
 [nan nan]]
[[nan nan  0.  0.]
 [nan nan nan  0.]
 [ 0. nan nan nan]
 [ 0.  0. nan nan]]
Q:  [[nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]]
a:  nan
b:  nan
r:  nan
G: 
 [[nan nan]
 [nan nan]]
[[nan nan  0.  0.]
 [nan nan nan  0.]
 [ 0. nan nan nan]
 [ 0.  0. nan nan]]
Q:  [[nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]]

Bottom most right 2x2 of matrix A:

[[nan nan]
 [nan nan]]
shift:  nan
a:  nan
b:  nan
r:  nan
G: 
 [[nan nan]
 [nan nan]]
[[nan nan  0.  0.]
 [nan nan nan  0.]
 [ 0. nan nan nan]
 [ 0.  0. nan nan]]
Q:  [[nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]]
a:  nan
b:  nan
r:  nan
G: 
 [[nan nan]
 [nan nan]]
[[nan nan  0.  0.]
 [nan nan nan  0.]
 [ 0. nan nan nan]
 [ 0.  0. nan nan]]
Q:  [[nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]]
a:  nan
b:  nan
r:  nan
G: 
 [[nan nan]
 [nan nan]]
[[nan nan  0.  0.]
 [nan nan nan  0.


Bottom most right 2x2 of matrix A:

[[nan nan]
 [nan nan]]
shift:  nan
a:  nan
b:  nan
r:  nan
G: 
 [[nan nan]
 [nan nan]]
[[nan nan  0.  0.]
 [nan nan nan  0.]
 [ 0. nan nan nan]
 [ 0.  0. nan nan]]
Q:  [[nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]]
a:  nan
b:  nan
r:  nan
G: 
 [[nan nan]
 [nan nan]]
[[nan nan  0.  0.]
 [nan nan nan  0.]
 [ 0. nan nan nan]
 [ 0.  0. nan nan]]
Q:  [[nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]]
a:  nan
b:  nan
r:  nan
G: 
 [[nan nan]
 [nan nan]]
[[nan nan  0.  0.]
 [nan nan nan  0.]
 [ 0. nan nan nan]
 [ 0.  0. nan nan]]
Q:  [[nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]]

Bottom most right 2x2 of matrix A:

[[nan nan]
 [nan nan]]
shift:  nan
a:  nan
b:  nan
r:  nan
G: 
 [[nan nan]
 [nan nan]]
[[nan nan  0.  0.]
 [nan nan nan  0.]
 [ 0. nan nan nan]
 [ 0.  0. nan nan]]
Q:  [[nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]]
a:  nan
b:  nan



Bottom most right 2x2 of matrix A:

[[nan nan]
 [nan nan]]
shift:  nan
a:  nan
b:  nan
r:  nan
G: 
 [[nan nan]
 [nan nan]]
[[nan nan  0.  0.]
 [nan nan nan  0.]
 [ 0. nan nan nan]
 [ 0.  0. nan nan]]
Q:  [[nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]]
a:  nan
b:  nan
r:  nan
G: 
 [[nan nan]
 [nan nan]]
[[nan nan  0.  0.]
 [nan nan nan  0.]
 [ 0. nan nan nan]
 [ 0.  0. nan nan]]
Q:  [[nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]]
a:  nan
b:  nan
r:  nan
G: 
 [[nan nan]
 [nan nan]]
[[nan nan  0.  0.]
 [nan nan nan  0.]
 [ 0. nan nan nan]
 [ 0.  0. nan nan]]
Q:  [[nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]]

Bottom most right 2x2 of matrix A:

[[nan nan]
 [nan nan]]
shift:  nan
a:  nan
b:  nan
r:  nan
G: 
 [[nan nan]
 [nan nan]]
[[nan nan  0.  0.]
 [nan nan nan  0.]
 [ 0. nan nan nan]
 [ 0.  0. nan nan]]
Q:  [[nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]]
a:  nan
b:  nan


[[nan nan  0.  0.]
 [nan nan nan  0.]
 [ 0. nan nan nan]
 [ 0.  0. nan nan]]
Q:  [[nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]]
a:  nan
b:  nan
r:  nan
G: 
 [[nan nan]
 [nan nan]]
[[nan nan  0.  0.]
 [nan nan nan  0.]
 [ 0. nan nan nan]
 [ 0.  0. nan nan]]
Q:  [[nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]]
a:  nan
b:  nan
r:  nan
G: 
 [[nan nan]
 [nan nan]]
[[nan nan  0.  0.]
 [nan nan nan  0.]
 [ 0. nan nan nan]
 [ 0.  0. nan nan]]
Q:  [[nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]]

Bottom most right 2x2 of matrix A:

[[nan nan]
 [nan nan]]
shift:  nan
a:  nan
b:  nan
r:  nan
G: 
 [[nan nan]
 [nan nan]]
[[nan nan  0.  0.]
 [nan nan nan  0.]
 [ 0. nan nan nan]
 [ 0.  0. nan nan]]
Q:  [[nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]]
a:  nan
b:  nan
r:  nan
G: 
 [[nan nan]
 [nan nan]]
[[nan nan  0.  0.]
 [nan nan nan  0.]
 [ 0. nan nan nan]
 [ 0.  0. nan nan]]
Q:  [[nan n

a:  nan
b:  nan
r:  nan
G: 
 [[nan nan]
 [nan nan]]
[[nan nan  0.  0.]
 [nan nan nan  0.]
 [ 0. nan nan nan]
 [ 0.  0. nan nan]]
Q:  [[nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]]

Bottom most right 2x2 of matrix A:

[[nan nan]
 [nan nan]]
shift:  nan
a:  nan
b:  nan
r:  nan
G: 
 [[nan nan]
 [nan nan]]
[[nan nan  0.  0.]
 [nan nan nan  0.]
 [ 0. nan nan nan]
 [ 0.  0. nan nan]]
Q:  [[nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]]
a:  nan
b:  nan
r:  nan
G: 
 [[nan nan]
 [nan nan]]
[[nan nan  0.  0.]
 [nan nan nan  0.]
 [ 0. nan nan nan]
 [ 0.  0. nan nan]]
Q:  [[nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]]
a:  nan
b:  nan
r:  nan
G: 
 [[nan nan]
 [nan nan]]
[[nan nan  0.  0.]
 [nan nan nan  0.]
 [ 0. nan nan nan]
 [ 0.  0. nan nan]]
Q:  [[nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]]

Bottom most right 2x2 of matrix A:

[[nan nan]
 [nan nan]]
shift:  nan
a:  nan
b:  nan


(array([[nan, nan, nan, nan],
        [nan, nan, nan, nan],
        [nan, nan, nan, nan],
        [nan, nan, nan, nan]]),
 None,
 array([[nan, nan, nan, nan],
        [nan, nan, nan, nan],
        [nan, nan, nan, nan],
        [nan, nan, nan, nan]]),
 array([[nan, nan, nan, nan],
        [nan, nan, nan, nan],
        [nan, nan, nan, nan],
        [nan, nan, nan, nan]]))